### PR TITLE
ESP32 OTA: check if device partition table is OTA compatible

### PR DESCRIPTION
**Pull request by pennam**

### CODE REVIEW

**Comment by BlastCom** [comment]
Hi, since this has been added, I got some issues with OTA.
Which version of OTA is needed to fix that error?
Thanks

.pio/libdeps/esp32dev/ArduinoIoTCloud/src/utility/ota/OTA-esp32.cpp: In function 'bool esp32_isOTACapable()':
.pio/libdeps/esp32dev/ArduinoIoTCloud/src/utility/ota/OTA-esp32.cpp:125:29: **error: 'isCapable' is not a member of 'Arduino_ESP32_OTA'**
   return Arduino_ESP32_OTA::isCapable();
                             ^~~~~~~~~
Compiling .pio\build\esp32dev\FrameworkArduino\Esp.cpp.o
*** [.pio\build\esp32dev\libfa3\ArduinoIoTCloud\utility\ota\OTA-esp32.cpp.o] Error 1

**Comment by pennam** [comment]
Hi @BlastCom 
which version of [Arduino_ESP32_OTA](https://github.com/arduino-libraries/Arduino_ESP32_OTA) are you using?
This method has been added in the last release of the library https://github.com/arduino-libraries/Arduino_ESP32_OTA/pull/19/files

**Comment by BlastCom** [comment]
My fault,
Thanks, PlatformIO didn't fetch the update.
Have a good day :)

**Comment by pennam** [comment]
Thanks for the feedback, have a good day too!

**Pull request merged**
