### PR TITLE
Added source codes of basic library

### PR DESCRIPTION
**Pull request by TomasRoj**
BasicsLibrary is library for beginners with examples. More info at my page. I want to contribute with you and implement your library to mine. I added your codes to my basiclibrary directory and implemented one example. Hope that we can code this library together and add your library examples to mine library.

### CODE REVIEW

**Comment by ubidefeo** [comment]
hi @TomasRoj 
I do not understand the reason for this PR.
@lxrobotics @cmaglie  do you?

**Comment by TomasRoj** [comment]
I want to use some of your examples to mine library for beginners. Reason for pr - new branch of my library you can add more examples etc

**Comment by ubidefeo** [comment]
@TomasRoj you can bring our code into your library without us needing to merge anything in

**Comment by TomasRoj** [comment]
Ok

**Pull request closed without merging**
