### PR TITLE
Change CloudTime from CloudFloat to CloudUnsignedInt

### PR DESCRIPTION
**Pull request by pennam**
This pr adds a new `CloudUnsignedInt` type and changes `CloudTime` from `CloudFloat` to `CloudUnsignedInt`

/cc @eclipse1985

### CODE REVIEW

**Comment by aentinger** [comment]
Good Morning @pennam :wave: :coffee: 
Possibly I've missed this, but did you extend the unit tests to also cover the new `CloudUnsignedInt`/`unsigned int` property?

**Comment by pennam** [comment]
Hi @aentinger, you are right, i did not add them. Let me do it :muscle:

**Comment by pennam** [comment]
@aentinger should be better now, i've added tests for encoding/decoding `CloudTime` property so it will cover also the `CloudUnsignedInt` type.

I was a bit unsure, but like for the other basic types (`CloudInt`, `CloudBool`...) i did not add any test for operator overloads.

**Comment by aentinger** [comment]
>@aentinger should be better now, i've added tests for encoding/decoding CloudTime property so it will cover also the CloudUnsignedInt type.

Yes, that's perfectly fine.

**Pull request merged**
