### PR TITLE
Enable RTC support for NANO_RP2040_CONNECT

### PR DESCRIPTION
**Pull request by pennam**
ArduinoCore-mbed has introduced support for RP2040 RTC and this patch makes it available for IoTCloud.

### CODE REVIEW

**Comment by aentinger** [comment]
Hi @pennam :wave: Where exactly (commit/PR) was RTC added to ArduinoCore-mbed  for RP2040?

**Comment by facchinm** [comment]
@aentinger https://github.com/arduino/ArduinoCore-mbed/commit/944e988d61841f5f2790ecc06e66df92354c984d :wink:

**Comment by pennam** [comment]
Hi @aentinger, the commint is not mainlined to mbed-os repo. It has been added as an extrapatch into our mbed core https://github.com/arduino/ArduinoCore-mbed/commit/944e988d61841f5f2790ecc06e66df92354c984d

**Review by aentinger — APPROVED** [review]
Thank you both (@facchinm and @pennam) for providing the commit. All looks good :+1: (That is to say, if it worked for H7 than most definitely it works for RP2040, provided that the RP2040 patch works). :+1:

**Pull request merged**
