### PR TITLE
Replace ArduinoIoTCloudBearSSL with ArduinoBearSSL

### PR DESCRIPTION
**Pull request by lxrobotics**

### CODE REVIEW

**Comment by ubidefeo** [comment]
Amazing job, @lxrobotics 🙏

**Comment by lxrobotics** [comment]
@ubidefeo - if only it would work. There seem to be some subtle differences between the two libraries -  investigating.

**Comment by lxrobotics** [comment]
@ubidefeo It works now :wink:

**Comment by ubidefeo** [comment]
must have been that early morning clarity 👌🏼

**Pull request closed without merging**
