### PR TITLE
Refactoring: Separating definition/implementation and other minor cleanups

### PR DESCRIPTION
**Pull request by lxrobotics**
No change in logic/functionality of the implementation.

### CODE REVIEW

**Comment by ubidefeo** [comment]
hi @lxrobotics 
I appreciate this effort a lot.
went through the code and it's cleaner, just want to test it a little today if you don't mind :)

**Comment by lxrobotics** [comment]
Hi @ubidefeo - please do so :+1: Let me know if you come across any issues :smiley:

**Comment by ubidefeo** [comment]
hey @lxrobotics 
would it trouble you to add a way to specify which Serial port can be used for the debug messages?
I haven't been able to get around it and I could benefit from having this option :)

**Comment by lxrobotics** [comment]
Sure, I can do that :+1: I'd prefer to do it in another pull request though and first merge and close this.

**Pull request merged**
