### PR TITLE
bin2ota Fix: Add missing colon

### PR DESCRIPTION
**Pull request by Jorgetrujilloroman**
Now it looks like:

elif board == "NICLA_VISION":

### CODE REVIEW

**Comment by per1234** [comment]
Thanks for your pull request @Jorgetrujilloroman!

> I have another problem: When I try to execute the bin2ota program, it show me an error:
>
> "ModuleNotFounfError: No module named 'crccheck'

Since it is not related to the code defect addressed here, please open a dedicated issue about the lack of documentation/infrastructure for managing the package dependency of this script.

**Comment by Jorgetrujilloroman** [comment]
Done, could fix the Module error by installing the crccheck module after install python pip on my ubuntu. Thank you very much.

**Comment by pennam** [comment]
Hi @Jorgetrujilloroman Thanks for the fix.
Can you please reword the commit description removing non relevant information?

Something like the PR title should be fine.

Thanks

**Review by pennam — CHANGES_REQUESTED** [review]
The fix is good, could you please reword the commit description as requested in the PR conversation?

**Review by pennam — APPROVED** [review]
LGTM

**Comment by jcarolinares** [comment]
Hey @pennam I don't have rights to merge this PR, could you please do it? :)

**Pull request merged**
