### PR TITLE
Change ntp/ping server to the arduino ones

### PR DESCRIPTION
**Pull request by eclipse1985**
Changed NTP and ping endpoints to `time.arduino.cc`

### CODE REVIEW

**Comment by eclipse1985** [comment]
Do not merge it for now

**Comment by facchinm** [comment]
For consistency should we also update it in the WiFi Connection Manager?

**Comment by eclipse1985** [comment]
Where do you mean? I don't see any reference to ping or ntp in WiFi Connection Manager

**Comment by facchinm** [comment]
Ah, wow, it was probably removed at some point. No issues then :wink:

**Pull request merged**
