### PR TITLE
Add Uno WiFi Rev2 to "Compile Examples" CI workflow

### PR DESCRIPTION
**Pull request by per1234**

### CODE REVIEW

**Comment by per1234** [comment]
I don't know enough about this code to determine whether the errors are legitimate or caused by a bad workflow configuration:

https://github.com/arduino-libraries/ArduinoIoTCloud/pull/209/checks?check_run_id=1411570685#step:9:82
```
  In file included from /github/home/Arduino/libraries/ArduinoIoTCloud/src/ArduinoIoTCloud.h:152:0,
                   from /tmp/arduino-sketch-0CD64181F5310E3579165DCB549C8EEE/sketch/thingProperties.h:1,
                   from /github/workspace/examples/ArduinoIoTCloud-Advanced/ArduinoIoTCloud-Advanced.ino:14:
  /github/home/Arduino/libraries/ArduinoIoTCloud/src/ArduinoIoTCloudTCP.h: At global scope:
  /github/home/Arduino/libraries/ArduinoIoTCloud/src/ArduinoIoTCloudTCP.h:111:5: error: 'WiFiBearSSLClient' does not name a type; did you mean 'WiFiSSLClient'?
       WiFiBearSSLClient _sslClient;
       ^~~~~~~~~~~~~~~~~
       WiFiSSLClient
```
https://github.com/arduino-libraries/ArduinoIoTCloud/pull/209/checks?check_run_id=1411570685#step:9:121
```
  /github/workspace/examples/ArduinoIoTCloud-Advanced/ArduinoIoTCloud-Advanced.ino: In function 'void setup()':
  /github/workspace/examples/ArduinoIoTCloud-Advanced/ArduinoIoTCloud-Advanced.ino:27:32: error: too few arguments to function 'void setDebugMessageLevel(int)'
     setDebugMessageLevel(DBG_INFO);
                                  ^
  In file included from /tmp/arduino-sketch-0CD64181F5310E3579165DCB549C8EEE/sketch/thingProperties.h:1:0,
                   from /github/workspace/examples/ArduinoIoTCloud-Advanced/ArduinoIoTCloud-Advanced.ino:14:
  /github/home/Arduino/libraries/ArduinoIoTCloud/src/ArduinoIoTCloud.h:158:6: note: declared here
   void setDebugMessageLevel(int const level);
        ^~~~~~~~~~~~~~~~~~~~
```
Please let me know if any changes are needed.

**Comment by aentinger** [comment]
Hi @per1234 :wave:
The 1st error concerning `WiFiBearSSLClient` is to be expected, since there is a pending PR [here](https://github.com/arduino-libraries/WiFiNINA/pull/139).
The 2nd error I'm not sure. I've seen that @facchinm removed Arduino_DebugUtils for the Uno WiFi Rev. 2 port, @facchinm why?

**Comment by facchinm** [comment]
I removed it to make all prints no-op and thus saving flash. Not sure if there's a better way since it seems that DBG_* is declared both here https://github.com/arduino-libraries/ArduinoIoTCloud/blob/master/src/AIoTC_Config.h#L33-L51 as a define and here https://github.com/arduino-libraries/Arduino_DebugUtils/blob/master/src/Arduino_DebugUtils.h#L33 as a constant.
I'd advise to change one of the two since right now it's very confusing.

**Comment by aentinger** [comment]
Wow, that's a good catch. I'm surprised those definitions didn't bite themselves yet. However, disabling all debug (and error output) across the whole library seems unfavourable to me. I'm wondering how you safely disabled debug output for AVR while keeping it safely enabled for all other platforms?

**Comment by facchinm** [comment]
@aentinger [this](https://github.com/arduino-libraries/ArduinoIoTCloud/pull/208/commits/0d47fbd9748885eba162c2ea133c478bef56db54#diff-a58f70185df6077493d1269b8b4dd09f6c20fe6907edfd8e317fd78de1dc1aa0R33-R41)  kicks in only for the uno wifi r2, and since the only other API excluding DBG* macros is `setDebugLevel` I implemented it here (https://github.com/arduino-libraries/ArduinoIoTCloud/pull/208/commits/0d47fbd9748885eba162c2ea133c478bef56db54#diff-4a6e083fb52e51c32948055d546936cdf5da314a3bf3f59a8117a167289ba6f2R183 , weak)

**Comment by aentinger** [comment]
I see now the problem. It's missing it's constants. Let me do a bit of cleanup altogether, I'm not too happy with this quick and dirty solution.

**Comment by aentinger** [comment]
All `Arduino_DebugUtils` related worries should have been taken care of with release of [0.5.1](https://github.com/arduino-libraries/Arduino_ConnectionHandler/releases/tag/0.5.1). Also a couple of commits have been made to https://github.com/arduino-libraries/ArduinoIoTCloud/tree/offload-ssl-nina-take2 . May I ask @per1234 to rebase this PR?

**Comment by per1234** [comment]
OK, rebase is done.

**Review by aentinger — APPROVED** [review]
LGTM :+1: Thank you @per1234 :rocket:

**Pull request merged**
