### PR TITLE
Refactoring ArduinoIoTCloud

### PR DESCRIPTION
**Pull request by aentinger**
Over the course of the `ArduinoIoTCloud` development a lot of clutter has gathered which makes it more difficult to use the existing code base to add something new on top (technical debt). This PR is touching many areas of the code but still tries to keep atomic commits as much as possible.

### CODE REVIEW

**Comment by aentinger** [comment]
Successfully tested on PROD with
* `MKR WAN 1310` :heavy_check_mark:
* `MKR GSM 1400` :heavy_check_mark:
* `MKR 1000` :heavy_check_mark:
* `MKR WiFi 1010` :heavy_check_mark:
* `ESP8266` :heavy_check_mark:

 @AlbyIanna
* Can you please test with `MKR WAN 1300/1310` and `MKR NB 1500`?
* Since this changes contains the changes of PR #108 it would be sufficient to check this PR and not check the old one. FYI: Since Provisioning.ino has been modified can you please check if the getting started process still works at it should (it should, but checking can't hurt).

**Comment by aentinger** [comment]
@Rocketct can you please test this PR with `MKR NB 1500`?

**Comment by Rocketct** [comment]
@aentinger yes 'l ask to our collegue in malmo and report as ASAP we will get some results

**Comment by Rocketct** [comment]
@aentinger our colleague test it and works properly, he test the things creation and data exchange between cloud and NB ad all works fine

**Comment by aentinger** [comment]
@Rocketct Thank you very much :+1:

**Pull request merged**
